In [1]:
import numpy as np

In [4]:
list_ = ['1','2','3','4','5']
array_list = np.array(list_)

In [8]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [5]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.

In [6]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [7]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [9]:
array_list = np.array(object = list_, dtype = int)

In [10]:
array_list

array([1, 2, 3, 4, 5])

In [11]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [12]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [13]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [14]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of <br>
variable num_array: <br>
(i) shape <br>
(ii) size <br>

In [15]:
num_array.shape

(2, 3)

In [16]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [18]:
arr = np.zeros((3,3))

In [19]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
arr.shape

(3, 3)

In [21]:
arr.size

9

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [22]:
arr1 = np.eye(5)

In [23]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])